// GENERATED by design-system/build.mjs from tokens.json. DO NOT EDIT. Change tokens.json and re-run.
//
// Use these through Theme / Typography / Components; views should not
// reach for raw numbers or hex values.

import SwiftUI
import UIKit

public enum DesignTokens {

    // MARK: Colors (light/dark adaptive; dark is PROVISIONAL)
    public enum Colors {
        /// Page/screen canvas
        public static let background = Color(light: 0xFFFFFF, dark: 0x000000)
        /// Primary text, icons, the mark
        public static let foreground = Color(light: 0x000000, dark: 0xFFFFFF)
        /// Cards, info panels, icon buttons, inputs
        public static let surface = Color(light: 0xF6F6F6, dark: 0x161616)
        /// Pressed/hover state of surface
        public static let surfaceHover = Color(light: 0xEFEFEF, dark: 0x1F1F1F)
        /// Primary CTA fill
        public static let primary = Color(light: 0x000000, dark: 0xFFFFFF)
        /// Text on primary CTA
        public static let primaryForeground = Color(light: 0xFFFFFF, dark: 0x000000)
        /// Labels, metadata, timestamps
        public static let mutedForeground = Color(light: 0x666666, dark: 0xA3A3A3)
        /// Only for text >= 18px or decorative
        public static let subtleForeground = Color(light: 0x8F8F8F, dark: 0x8F8F8F)
        /// Hairlines, dividers
        public static let border = Color(light: 0xE6E6E6, dark: 0x262626)
        /// Count/streak badges ONLY
        public static let highlight = Color(light: 0x91CDFF, dark: 0x91CDFF)
        /// Text on highlight
        public static let highlightForeground = Color(light: 0x000000, dark: 0x000000)
        /// Errors, destructive actions (proposed)
        public static let destructive = Color(light: 0xC0281C, dark: 0xFF6B5E)
        /// Text on destructive
        public static let destructiveForeground = Color(light: 0xFFFFFF, dark: 0x000000)
        /// Focus ring
        public static let ring = Color(light: 0x000000, dark: 0xFFFFFF)
    }

    // MARK: Typography (one weight: Medium)
    public struct TextStyleToken {
        public let size: CGFloat          // pt at default Dynamic Type size
        public let lineHeight: CGFloat    // multiplier
        public let tracking: CGFloat      // pt (already converted from em)
        public let textStyle: Font.TextStyle // Dynamic Type style to scale with
        public var lineSpacing: CGFloat { max(0, size * lineHeight - size) }
    }
    public static let fontWeight: Font.Weight = .medium // 500
    public static let brandFontName = "PP Neue Montreal"
    public static let fallbackFontName = "Inter Display"
    public enum TextStyles {
        public static let display = TextStyleToken(size: 44, lineHeight: 0.95, tracking: -1.98, textStyle: .largeTitle)
        public static let h1 = TextStyleToken(size: 34, lineHeight: 1, tracking: -1.19, textStyle: .largeTitle)
        public static let h2 = TextStyleToken(size: 28, lineHeight: 1.05, tracking: -0.84, textStyle: .title)
        public static let h3 = TextStyleToken(size: 22, lineHeight: 1.15, tracking: -0.44, textStyle: .title2)
        public static let title = TextStyleToken(size: 18, lineHeight: 1.25, tracking: -0.18, textStyle: .title3)
        public static let body = TextStyleToken(size: 16, lineHeight: 1.45, tracking: -0.08, textStyle: .body)
        public static let label = TextStyleToken(size: 14, lineHeight: 1.35, tracking: 0, textStyle: .subheadline)
        public static let caption = TextStyleToken(size: 12, lineHeight: 1.35, tracking: 0.06, textStyle: .caption)
    }

    // MARK: Shape
    public enum Radius {
        public static let sm: CGFloat = 8 // Chips, thumbnails
        public static let md: CGFloat = 12 // Info cards, inputs
        public static let lg: CGFloat = 16 // Cards, notification cards, photos
        public static let xl: CGFloat = 24 // Sheets, large photo frames
        public static let x2xl: CGFloat = 40 // Hero photos, selfie 'pebble' frame
        public static let full: CGFloat = 9999 // Pills and circles (all buttons)
    }

    // MARK: Spacing (4pt grid)
    public enum Space {
        public static let s1: CGFloat = 4
        public static let s2: CGFloat = 8
        public static let s3: CGFloat = 12
        public static let s4: CGFloat = 16
        public static let s6: CGFloat = 24
        public static let s8: CGFloat = 32
        public static let s12: CGFloat = 48
        public static let s16: CGFloat = 64
        public static let s24: CGFloat = 96
    }

    public enum Size {
        public static let controlHeight: CGFloat = 48 // Buttons, inputs
        public static let iconButton: CGFloat = 48 // Circular icon button
        public static let minTouch: CGFloat = 44 // Minimum tap target (Android: use 48dp)
        public static let icon: CGFloat = 22 // Default icon size
        public static let thumbnail: CGFloat = 64 // Notification thumbnail
    }

    // MARK: Elevation: only floating layers (sheets, popovers). Cards are flat.
    public enum Shadow {
        public static let floatColor = Color.black.opacity(0.18)
        public static let floatRadius: CGFloat = 32
        public static let floatY: CGFloat = 24
    }

    // MARK: Motion. Opacity-only reveals; respect Reduce Motion.
    public enum Motion {
        public static let fast: Double = 0.15 // Press, toggle (proposed)
        public static let base: Double = 0.3 // Hover/tap reveal, crossfade (measured ~270-300ms)
        public static let slow: Double = 0.75 // Brand reveals (measured ~730-770ms)
        public static let stagger: Double = 0.8 // Delay between items in a brand reveal
        public static let boil: Double = 0.12 // Hand-drawn boil frame interval of the mark (~8fps)
        /// Gentle decelerate, no overshoot
        public static func easeOut(_ duration: Double = base) -> Animation { .timingCurve(0.3, 0.7, 0.4, 1, duration: duration) }
        /// Wipes/exits
        public static func easeInOut(_ duration: Double = base) -> Animation { .timingCurve(0.65, 0, 0.35, 1, duration: duration) }
    }
}

private extension Color {
    init(light: UInt32, dark: UInt32) {
        func ui(_ v: UInt32) -> UIColor {
            UIColor(red: CGFloat((v >> 16) & 0xFF) / 255, green: CGFloat((v >> 8) & 0xFF) / 255, blue: CGFloat(v & 0xFF) / 255, alpha: 1)
        }
        self.init(uiColor: UIColor { $0.userInterfaceStyle == .dark ? ui(dark) : ui(light) })
    }
}
